### ISSUE TITLE
How to get the parameters on the URL?

### ISSUE THREAD

**Issue by damiaozi** [agrcrobles/react-native-web-boilerplate#11]
I use react-navigation Do interface jump.
but,now，I want to get the parameters on the URL。
How to get the parameters on the URL?

**Comment by agrcrobles** [comment]
Hi,

In order to rewrite the url, ( add history etc ) you will have to implement your custom [BrowserAppContainer](https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js) in your web app.

I remind you it is suggested not using native navigators on web. You can create your custom navigation extending either TabRouter or StackRouter.

If you can make the URL rewrite working without REDUX, feel free to send a PR, I can review it.

Thanks

**Comment by agrcrobles** [comment]
Hi,

In order to rewrite the url, ( add history etc ) you will have to implement your custom [BrowserAppContainer](https://github.com/react-community/react-navigation/blob/master/website/src/BrowserAppContainer.js) in your web app.

I remind you it is suggested not using native navigators on web. You can create your custom navigator extending either TabRouter or StackRouter.

If you can make the URL rewrite work without REDUX, feel free to send a PR, I can review it.

Thanks

**Comment by damiaozi** [comment]
I get parameters by this way.but I do not know whether this is a viable way
```
 export function paraURL(paramName) {
    paramValue = "", isFound = !1;  
    if (this.location.search.indexOf("?") == 0 && this.location.search.indexOf("=") > 1) {  
        arrSource = unescape(this.location.search).substring(1, this.location.search.length).split("&"), i = 0;  
        while (i < arrSource.length && !isFound) arrSource[i].indexOf("=") > 0 && arrSource[i].split("=")[0].toLowerCase() == paramName.toLowerCase() && (paramValue = arrSource[i].split("=")[1], isFound = !0), i++  
    }  
    return paramValue == "" && (paramValue = null), paramValue  

}
```
